# Generated by Django 6.1 on 2026-08-09 11:26

import accounts.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_path, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Femme'), ('M', 'Homme'), ('A', 'Autre'), ('N', 'Ne se prononce pas')], default='N', help_text="Utilisé pour adapter les recommandations d'entraînement.", max_length=1, verbose_name='sexe'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(260)], verbose_name='taille (cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('25.0')), django.core.validators.MaxValueValidator(Decimal('350.0'))], verbose_name='poids (kg)'),
        ),
    ]
