# Generated by Django 6.1 on 2026-08-09 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(choices=[('body only', 'Poids du corps'), ('barbell', 'Barre'), ('dumbbell', 'Haltères'), ('kettlebells', 'Kettlebell'), ('cable', 'Poulie'), ('machine', 'Machine'), ('bands', 'Élastiques'), ('e-z curl bar', 'Barre EZ'), ('medicine ball', 'Médecine ball'), ('exercise ball', 'Ballon de gym'), ('foam roll', 'Rouleau de massage'), ('other', 'Autre')], max_length=16, verbose_name='matériel')),
                ('mode', models.CharField(choices=[('bodyweight', 'Sans charge'), ('fixed', 'Charges figées'), ('adjustable', 'Charge réglable')], default='bodyweight', max_length=12, verbose_name='charges')),
                ('weights', models.JSONField(blank=True, default=list, verbose_name='charges disponibles')),
                ('min_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='charge minimale')),
                ('max_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='charge maximale')),
                ('step_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='incrément')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'matériel',
                'verbose_name_plural': 'matériel',
                'ordering': ('equipment',),
                'constraints': [models.UniqueConstraint(fields=('user', 'equipment'), name='unique_equipment_per_user')],
            },
        ),
    ]
