# Generated by Django 6.1 on 2026-08-11 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userequipment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userequipment",
            options={
                "ordering": ("id",),
                "verbose_name": "matériel",
                "verbose_name_plural": "matériel",
            },
        ),
    ]
