# Generated by Django 6.1.1 on 2026-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userequipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_enabled',
            field=models.BooleanField(default=True, help_text='Affiche le groupe Apple Santé dans le menu (issue #104).', verbose_name='Apple Santé activée'),
        ),
    ]
