# Generated by Django 6.1 on 2026-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='identifiant')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'muscle',
                'verbose_name_plural': 'muscles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identifiant')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('category', models.CharField(choices=[('strength', 'Renforcement'), ('stretching', 'Étirement'), ('plyometrics', 'Pliométrie'), ('powerlifting', 'Force athlétique'), ('olympic weightlifting', 'Haltérophilie'), ('strongman', 'Strongman'), ('cardio', 'Cardio')], max_length=24, verbose_name='catégorie')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('expert', 'Confirmé')], max_length=16, verbose_name='niveau')),
                ('force', models.CharField(blank=True, choices=[('push', 'Poussée'), ('pull', 'Tirage'), ('static', 'Statique')], max_length=8, verbose_name="type d'effort")),
                ('mechanic', models.CharField(blank=True, choices=[('compound', 'Polyarticulaire'), ('isolation', 'Isolation')], max_length=12, verbose_name='mécanique')),
                ('equipment', models.CharField(blank=True, choices=[('body only', 'Poids du corps'), ('barbell', 'Barre'), ('dumbbell', 'Haltères'), ('kettlebells', 'Kettlebell'), ('cable', 'Poulie'), ('machine', 'Machine'), ('bands', 'Élastiques'), ('e-z curl bar', 'Barre EZ'), ('medicine ball', 'Médecine ball'), ('exercise ball', 'Ballon de gym'), ('foam roll', 'Rouleau de massage'), ('other', 'Autre')], max_length=16, verbose_name='matériel')),
                ('instructions', models.JSONField(blank=True, default=list, verbose_name='consignes')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='illustrations')),
                ('primary_muscles', models.ManyToManyField(blank=True, related_name='exercises_as_primary', to='exercises.muscle', verbose_name='muscles principaux')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='exercises_as_secondary', to='exercises.muscle', verbose_name='muscles secondaires')),
            ],
            options={
                'verbose_name': 'exercice',
                'verbose_name_plural': 'exercices',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['category', 'level'], name='exercises_e_categor_55316b_idx'), models.Index(fields=['equipment'], name='exercises_e_equipme_ab2632_idx')],
            },
        ),
    ]
