# Generated by Django 6.0.1 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions_fr',
            field=models.JSONField(blank=True, default=list, verbose_name='consignes (français)'),
        ),
    ]
