# Generated by Django 6.1 on 2026-08-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], verbose_name='durée')),
                ('format', models.CharField(choices=[('hiit', 'HIIT — intervalles intenses'), ('tabata', 'Tabata — 20 s / 10 s'), ('circuit', 'Circuit training'), ('pyramid', 'Pyramide')], max_length=12, verbose_name='type de travail')),
                ('favorites_ratio', models.PositiveSmallIntegerField(default=25, help_text="Pourcentage d'exercices puisés dans les favoris.", verbose_name='part de favoris')),
                ('planned_seconds', models.PositiveIntegerField(default=0, verbose_name='durée planifiée')),
                ('coaching_notes', models.TextField(blank=True, verbose_name='conseils')),
                ('muscles', models.ManyToManyField(blank=True, to='exercises.muscle', verbose_name='parties du corps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'séance',
                'verbose_name_plural': 'séances',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='position')),
                ('block_index', models.PositiveSmallIntegerField(default=0, verbose_name='bloc')),
                ('block_label', models.CharField(blank=True, max_length=60, verbose_name='intitulé du bloc')),
                ('rounds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='séries')),
                ('work_seconds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='effort (s)')),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='repos (s)')),
                ('reps', models.JSONField(blank=True, default=list, verbose_name='répétitions')),
                ('loads', models.JSONField(blank=True, default=list, verbose_name='charges (kg)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'exercice de séance',
                'verbose_name_plural': 'exercices de séance',
                'ordering': ('position',),
            },
        ),
    ]
