# Generated by Django 6.1 on 2026-08-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='favori'),
        ),
        migrations.AddField(
            model_name='workout',
            name='rest_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='repos demandé (s)'),
        ),
        migrations.AddField(
            model_name='workout',
            name='work_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='effort demandé (s)'),
        ),
    ]
