# Generated by Django 6.1 on 2026-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_work_rest_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='nom'),
        ),
    ]
