# Generated by Django 6.1 on 2026-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(choices=[(10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (25, '25 minutes'), (30, '30 minutes'), (35, '35 minutes'), (40, '40 minutes'), (45, '45 minutes'), (50, '50 minutes'), (55, '55 minutes'), (60, '60 minutes')], verbose_name='durée'),
        ),
    ]
