# Generated by Django 6.1 on 2026-08-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='peak_reps',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pic de répétitions demandé'),
        ),
    ]
