# Generated by Django 6.1 on 2026-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0005_workout_peak_reps"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="recovery_seconds",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="repos entre les tours (s)"
            ),
        ),
    ]
