# Generated by Django 6.1 on 2026-08-09 09:55

import aiproviders.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral AI'), ('ollama', 'Ollama (local)')], max_length=32, unique=True, verbose_name='fournisseur')),
                ('secret', aiproviders.fields.EncryptedTextField(blank=True, verbose_name="clé d'API")),
                ('base_url', models.URLField(blank=True, verbose_name='URL de base')),
                ('default_model', models.CharField(blank=True, max_length=100, verbose_name='modèle par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'credential IA',
                'verbose_name_plural': 'credentials IA',
                'ordering': ('provider',),
            },
        ),
    ]
