# Generated by Django 6.1 on 2026-08-25 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Course à pied'), ('walking', 'Marche'), ('cycling', 'Vélo'), ('swimming', 'Natation'), ('hiking', 'Randonnée'), ('strength_training', 'Musculation'), ('rowing', 'Aviron'), ('elliptical', 'Vélo elliptique'), ('yoga', 'Yoga'), ('other', 'Autre')], default='other', max_length=24, verbose_name='type')),
                ('started_at', models.DateTimeField(verbose_name='débutée le')),
                ('ended_at', models.DateTimeField(verbose_name='terminée le')),
                ('distance_meters', models.FloatField(blank=True, null=True, verbose_name='distance (m)')),
                ('active_energy_kcal', models.FloatField(blank=True, null=True, verbose_name='énergie active (kcal)')),
                ('average_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FC moyenne (bpm)')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ('-started_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_type', 'started_at'), name='unique_activity_start')],
            },
        ),
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(verbose_name='mesurée le')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='poids (kg)')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'mesure de poids',
                'verbose_name_plural': 'mesures de poids',
                'ordering': ('-recorded_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'recorded_at'), name='unique_weight_per_instant')],
            },
        ),
    ]
