# Generated by Django 6.1 on 2026-08-25 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='nom')),
                ('prefix', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='préfixe')),
                ('hashed_key', models.CharField(max_length=128, verbose_name='clé (hachée)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière utilisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'clé API',
                'verbose_name_plural': 'clés API',
                'ordering': ('-created_at',),
            },
        ),
    ]
