# Generated by Django 6.1 on 2026-08-26 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('steps', models.PositiveIntegerField(verbose_name='pas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_steps', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'total de pas quotidien',
                'verbose_name_plural': 'totaux de pas quotidiens',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_steps')],
            },
        ),
    ]
