# Generated by Django 6.1 on 2026-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_dailysteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='durée (s)'),
            preserve_default=False,
        ),
    ]
