# Generated by Django 6.1 on 2026-08-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_activity_duration_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weight', 'Poids'), ('activity', 'Activité')], max_length=8, verbose_name='catégorie')),
                ('natural_key', models.CharField(db_index=True, max_length=255, verbose_name='clé naturelle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_imports', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "exclusion d'import",
                'verbose_name_plural': "exclusions d'import",
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'natural_key'), name='unique_excluded_import')],
            },
        ),
    ]
